title: "Log-Time Quantum Gravity"
description: "Unifying General Relativity and Quantum Mechanics through logarithmic time coordinates"
url: "https://denzilgreenwood.github.io"
baseurl: "/log_time"

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files
exclude:
  - vendor
  - .bundle
  - .sass-cache
  - _site
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md